<template>
  <div class="mainBlock">
    <div></div>
    <div>
      <p style="text-align: center;">
        <strong>
          <u>
            <span
              style="font-family: 'Calibri',sans-serif;"
            >Klanik SA - Avenue Louise 209a, 1050 Brussels BCE 0660.949.090</span>
          </u>
        </strong>
      </p>
      <p style="text-align: center;">
        <span
          style="font-family: 'Calibri',sans-serif;"
        >GDPR Consent form for candidates for the processing of Personal Data</span>
      </p>

      <p style="text-align: justify;">
        <span
          style="font-family: 'Calibri',sans-serif;"
        >Klanik takes its obligations to protect personal information it collects as part of its activities very seriously. Under the EU General Data Protection Regulation 2016/679 on the protection of personal data (GDPR), Klanik is committed to acting with the highest degree of professionalism and transparency with your personal data.</span>
      </p>

      <p style="text-align: justify;">
        <strong>
          <span style="font-family: 'Calibri',sans-serif;">Definitions:</span>
        </strong>
      </p>
      <ul>
        <li>
          <u>
            <span style="font-family: 'Calibri',sans-serif;">Personal Data</span>
          </u>
          <span
            style="font-family: 'Calibri',sans-serif;"
          >: any information relating to an identified or identifiable natural person, such as a name, an identification number, location data, or photo; for the purposes of this consent, the main forms of Personal Data are those found in your</span>
          <span style="font-family: 'Calibri',sans-serif;">Curriculum Vitae (CV)</span>
          <span
            style="font-family: 'Calibri',sans-serif;"
          >, and if/when required, those necessary for your employment</span>
        </li>
        <li>
          <u>
            <span style="font-family: 'Calibri',sans-serif;">Processing</span>
          </u>
          <span
            style="font-family: 'Calibri',sans-serif;"
          >: any operation performed on Personal Data such as collection, recording, storage, use, or transmission; for the purposes of this consent, the main forms of Processing by Klanik are the organisation, analysis and transmission of your CV and candidate information to clients and potential clients of Klanik</span>
        </li>
        <li>
          <u>
            <span style="font-family: 'Calibri',sans-serif;">Consent</span>
          </u>
          <span
            style="font-family: 'Calibri',sans-serif;"
          >: a freely given, specific, informed and unambiguous indication of the data subject's wishes by which he or she, by accepting this form, signifies agreement to the Processing of Personal Data relating to him or her, including specifically the Processing of Personal Data as described herein</span>
        </li>
      </ul>

      <ol>
        <li>
          <strong>
            <span
              style="font-family: 'Calibri',sans-serif;"
            >Purposes of the Processing of the your Personal Data</span>
          </strong>
        </li>

        <p style="text-align: justify;">
          <span
            style="font-family: 'Calibri',sans-serif;"
          >Your collected Personal Data will be Processed with your Consent for the following purposes:</span>
        </p>

        <ul>
          <li>
            <span
              style="font-family: 'Calibri',sans-serif;"
            >Assessment of the suitability of your profile for vacancies available at Klanik, and participation in the recruitment / application process.</span>
            <span
              style="font-family: 'Calibri',sans-serif;"
            >In this regard the following Personal Data will be Processed:</span>
          </li>
          <ul>
            <li>
              <span
                style="font-family: 'Calibri',sans-serif;"
              >personal information: such as name, nationality, date of birth, gender, photograph, and contact details for instance postal address and e-mail address, phone number</span>
            </li>
            <li>
              <span
                style="font-family: 'Calibri',sans-serif;"
              >professional information collected via the candidate&rsquo;s CV</span>
            </li>
          </ul>
        </ul>

        <ul>
          <li>
            <span
              style="font-family: 'Calibri',sans-serif;"
            >Performance of administrative tasks/follow-up, such as filling out in Klanik&rsquo;s candidate database the candidate information during interviews, collected in person (face-to-face or over telephone), electronically by e-mail or by submission through the Klanik website.</span>
            <span
              style="font-family: 'Calibri',sans-serif;"
            >In this regard the following data will be collected and processed:</span>
          </li>
          <ul>
            <li>
              <span
                style="font-family: 'Calibri',sans-serif;"
              >personal information, such as education, experiences, languages spoken, career expectations, mobility, salary package</span>
            </li>
          </ul>
        </ul>

        <p style="text-align: justify;">
          <span
            style="font-family: 'Calibri',sans-serif;"
          >Your Personal Data will not be used for another purpose unless Klanik specifically asks for your Consent.</span>
        </p>

        <li>
          <strong>
            <span
              style="font-family: 'Calibri',sans-serif;"
            >Storage of the candidate&rsquo;s Personal Data</span>
          </strong>
        </li>

        <p style="text-align: justify;">
          <span
            style="font-family: 'Calibri',sans-serif;"
          >Your Personal Data will be stored in a secured, protected and professionally-run electronic database located within the European Economic Area. Confidential access to Personal Data on a need to know basis will be limited to the human resources, finance, administrative and business management functions within Klanik.</span>
        </p>

        <p style="text-align: ;">
          <span
            style="font-family: 'Calibri',sans-serif;"
          >Depending on your profile and the application process, your Personal Data will be stored as described above for a duration of up to two years after the last contact with you.</span>
        </p>

        <p style="text-align: ;">
          <span style="font-family: 'Calibri',sans-serif;">After this period, Klanik will either:</span>
        </p>
        <ul>
          <li>
            <span
              style="font-family: 'Calibri',sans-serif;"
            >Contact you again to confirm once more your consent to store your Personal Data, or</span>
          </li>
          <li>
            <span
              style="font-family: 'Calibri',sans-serif;"
            >delete your Personal Data from our systems.</span>
          </li>
        </ul>

        <p style="text-align: justify;">
          <span
            style="font-family: 'Calibri',sans-serif;"
          >Klanik does not store sensitive Personal Data such as race, medical information, religion, sexual orientation or criminal records. Klanik does not store Personal Data of minors.</span>
        </p>

        <p style="text-align: ;">
          <span
            style="font-family: 'Calibri',sans-serif;"
          >Please note that if your application leads to an employment at Klanik, your Personal Data collected during your pre-employment period and the data which remain necessary for the execution of the contract will be kept according to Klanik&rsquo;s internal privacy policy.</span>
        </p>
        <p style="text-align: ;">
          <span style="font-family: 'Calibri',sans-serif;">&nbsp;</span>
        </p>
        <li>
          <strong>
            <span
              style="font-family: 'Calibri',sans-serif;"
            >Sharing and transferring of the candidate&rsquo;s Personal Data</span>
          </strong>
        </li>

        <p style="text-align: ;">
          <span
            style="font-family: 'Calibri',sans-serif;"
          >Outside of the storage of your Personal Data at our data hosting provider, Klanik will never transfer Personal Data to non-business related third parties or to direct marketing organizations. The Personal Data you provide to Klanik may be transferred internally within our organisation and also via email among Klanik staff located in our offices (Marseille, Brussels, Sophia Antipolis, Lyon, Paris, Montpellier).</span>
        </p>

        <p style="text-align: ;">
          <span
            style="font-family: 'Calibri',sans-serif;"
          >All your Personal Data will remain confidential and will only be disclosed to our customers with an appropriate notification to the candidate.</span>
        </p>

        <p style="text-align: ;">
          <span
            style="font-family: 'Calibri',sans-serif;"
          >Please note that some clients may request additional information besides the details found in your CV / technical file (such as a copy of your identity card for security reasons).</span>
        </p>

        <p style="text-align: ;">
          <span
            style="font-family: 'Calibri',sans-serif;"
          >In addition, please note that Klanik may have the legal obligation to share your details with government officials when legal reporting requirements are in effect, or law enforcement agencies or private litigants in response to valid law enforcement process.</span>
        </p>

        <li>
          <strong>
            <span
              style="font-family: 'Calibri',sans-serif;"
            >Withdrawal of the candidate&rsquo;s Consent</span>
          </strong>
        </li>

      <p style="text-align: ;">
        <span
          style="font-family: 'Calibri',sans-serif;"
        >You may, at any time, decide to withdraw your consent. This may be done by simply going to the GDPR tab and unchecking the box.</span>
      </p>

      <p style="text-align: ;">
        <strong>
          <span
            style="font-family: '',sans-serif;"
          >ATTENTION: doing this will delete your Personal Data from the Klanik database; Klanik would then be incapable of Processing the Personal Data as described above.</span>
        </strong>
      </p>

      <p style="text-align: justify;">
        <span
          style="font-family: 'Calibri',sans-serif;"
        >Our Privacy notice outlines the use and management of your Personal Data in further details and is available at</span>
        <a href="http://www.klanik.com">
          <span style="font-family: 'Calibri',sans-serif;">www.klanik.com</span>
        </a>
        <span style="font-family: 'Calibri',sans-serif;">.</span>
      </p>

      <p style="text-align: ;">
        <span
          style="font-family: 'Calibri',sans-serif;"
        >By clicking &ldquo;Accept&rdquo; below, you confirm that you understand and freely consent to provide your Personal Data to Klanik as described above.</span>
      </p>

      <p style="text-align: ;">
        <span
          style="font-family: 'Calibri',sans-serif;"
        >By accepting this form, the candidate acknowledges that he/she:</span>
      </p>
      <ul>
        <li>
          <span
            style="font-family: 'Calibri',sans-serif;"
          >is informed of which Personal Data pertaining to the candidate that Klanik will use</span>
        </li>
        <li>
          <span
            style="font-family: 'Calibri',sans-serif;"
          >is informed of the reason for Processing of this Personal Data by Klanik</span>
        </li>
        <li>
          <span
            style="font-family: 'Calibri',sans-serif;"
          >understands and freely and unambiguously agrees to this Processing as described above</span>
        </li>
      </ul>
      </ol>

    </div>
    <div></div>
    <div></div>

   
     <div>
      <b-button variant="success" v-on:click="SetOptIn()">Accept</b-button>
      <!-- <input
        type="checkbox"
        name="gprdOptIn"
        id="gprdOptIn"
        v-model="OptedIn"
        v-on:change="SetOptIn()"
      /> -->
      <!-- OptIn : {{OptedIn}} -->
    </div>
    <div></div>

  </div>
</template>

<script>
import authenticationService from "@/services/AuthenticationService";

export default {
  name: "GDPR",
  component: {},

  data() {
    return {
      OptedIn: this.$store.getters.GetOptIn
    };
  },
  methods: {
    async SetOptIn() {
      if(typeof this.OptedIn == 'undefined'){
        this.OptedIn = false;
      }else{
        this.OptedIn = !this.OptedIn;
      }
 
      await this.$store.dispatch("SetOptIn", this.OptedIn);
      await authenticationService.updateOptIn(
        this.$store.getters.currentUser.sub,
        this.$store.getters.GetOptIn
      ).then(()=>{this.$toastr('success', 'GDPR updated', '');});
    }
  }
};
</script>

<style >
.mainBlock {
  margin-top: 15px;
  display: grid;
  grid-template-columns: 1fr 2fr 1fr;
  grid-column-gap: 5 px;
  grid-row-gap: 15px;
}
</style>
